services:
  - docker:dind
  
stages:          # List of stages for jobs, and their order of executions
  #- build
  - publish 
  


push-docker-registry:
  image: docker:latest
  stage: publish
  script:
    - docker login -u dev_ci -p $token git.qeema.io:5050
    - docker build -t git.qeema.io:5050/qeema-platfrom/demo_repo:latest -t git.qeema.io:5050/qeema-platfrom/demo_repo:3 .
    
    - docker push git.qeema.io:5050/qeema-platfrom/demo_repo --all-tags




